baseURL = "https://trustd.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "TrustD Solutions"
[markup.goldmark.renderer]
unsafe = true
