[en]
contentDir = "content/english"
copyright = "© 2021 TrustD Solutions. All Rights Reserved"
footer_content = "DevOps Experts to Scale up your business\vnot your costs."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "TrustD Solutions"
weight = "1"
