footer_middle = []
footer_right = []
[[footer_left]]
name = "Home"
url = "/"
[[footer_left]]
name = "Contact"
url = "contact"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Contact"
url = "contact"
weight = 4
