[[footer_left]]
name = "About Us"
url = "#"
[[footer_left]]
name = "Quick Start"
url = "#"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Contact"
url = "contact"
weight = 4
[[main]]
name = "FAQ"
url = "faq"
weight = 5
