author = "TrustD"
contact_form_action = "#"
description = "DevOps Experts"
logo = "images/logo.png"
logo_width = "200px"
social = []
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
